name: Hermes Testing
on: [push]
jobs:
  TestingAndLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup
        run: | 
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          export PATH="$HOME/.poetry/bin:${PATH}"
          poetry install

      - name: PyLint
        if: always()
        run: poetry run ./tests.sh pylint
      
      - name: Flake8
        if: always()
        run: poetry run ./tests.sh flake8

      - name: Mypy
        if: always()
        run: poetry run ./tests.sh mypy

      - name: Coverage 95%
        if: always()
        run: poetry run ./tests.sh coverage95

      - name: Server
        if: always()
        run: timeout --preserve-status -s SIGINT 5 poetry run uvicorn hermes.endpoints:app --reload

      - name: Docker minimal
        if: always()
        run: |
          docker build . -t 23jura23/hermes_se2021:ci
          timeout --preserve-status -s SIGINT 15 docker run -p 8000:8000 23jura23/hermes_se2021:ci &
          wget http://127.0.0.1:8000/statistics/mean_age/ever_married/Yes

      - name: Docker tests
        if: always()
        run: |
          docker build . -t 23jura23/hermes_se2021:ci_tests -f test/Dockerfile
          docker run -p 8000:8000 23jura23/hermes_se2021:ci_tests