name: Hermes Testing
on: [push]
jobs:
  TestingAndLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup
        run: ./init.sh python3

      - name: PyLint
        if: always()
        run: ./tests.sh pylint
      
      - name: Flake8
        if: always()
        run: ./tests.sh flake8

      - name: Mypy
        if: always()
        run: ./tests.sh mypy

      - name: Coverage 95%
        if: always()
        run: |
          coverage run -m pytest test
          coverage report --fail-under 95

