name: Hermes Testing
on: [push]
jobs:
  TestingAndLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: python -m pip install -r requirements.txt

      - name: pylint
        run: python3 -m pylint hermes test

      - name: flake8
        run: python3 -m flake8 hermes test

      - name: mypy
        run: python3 -m mypy hermes test

      - name: coverage 95%
        run: coverage run -m pytest test
        run: coverage report --fail-under 95

