name: Hermes Testing
on: [push]
jobs:
  TestingAndLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup
        run: python -m pip install -r requirements.txt

      - name: PyLint
        if: always()
        run: python3 -m pylint --max-line-length=120 --disable=invalid-name,missing-docstring,global-statement,too-many-lines,R,no-member --enable=simplifiable-if-statement,redefined-variable-type hermes test
      
      - name: Flake8
        if: always()
        run: python3 -m flake8 --max-line-length=120 hermes test

      - name: Mypy
        if: always()
        run: python3 -m mypy --ignore-missing-imports hermes test

      - name: Coverage 95%
        if: always()
        run: |
          coverage run -m pytest test
          coverage report --fail-under 95

